# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d9cb8c047cfc209a4293cccc502b7b1e3ec4aa3a7db40335f402ff9482d964f5cb01ab4c809e7e6c10d5f6732a1d2129225a416dceda0b2dfbf40185502d48

test:
  secret_key_base: 3a527325b5d7c1cd6eac6c3c549d188f00e4c89e11d5a8b4a5c289489d0f618678882859877c47bfcf15c5c8ccba15034f680099dc47de866396d61016b0fbdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
